services:
  bank-mysql:
    image: mysql:8.0
    container_name: bank-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_app_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: bank-mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - bank-mysql

volumes:
  mysql_data: